# Site settings
title: Nicolas Porcel's Blog
email: nicolas@porcel.me
description: >
  This blog describes the different projects I made and talking
  mostly about programing, Linux and Open Source software.
baseurl: ""
url: "http://nicolas.porcel.me"
twitter_username: NicolasPorcel06
github_username: Nicop06

# Build settings
markdown: kramdown
#permalink: pretty
